- name: Declare a Variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare a Variable in another file
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: Access a variable from a file
      ansible.builtin.debug:
        msg: URL == {{URL}}

## vars_files can also be declared at task level

- name: Declare a Variable in another file
  hosts: all
  connection: local
  tasks:
    - name: Declare var file variable on task level
      ansible.builtin.debug:
        msg: URL == {{URL}}



- name: Declare a Variable at play level
  hosts: all
  connection: local
  tasks:
    - name: Access a Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task.example.com