- name: Demo on Loops
  hosts: all
  connection: local
  tasks:
    - name: Print Fruit Name
      debug:
        msg: Fruit Name is {{ item }}
      loop:
        - Apple
        - Banana
    - name: Print Fruit Name & Quantity means Map
      debug:
        msg: Fruit Name is {{ item.name }}, & Quantity is {{ item.value }}
      loop:
        - { name: "Apple" , value: 100 }
        - { name: "Banana" , value: 200 }