# Pass fruit_name from command line
- name: Demo on Conditions
  hosts: all
  connection: local
  tasks:
    - name: String Conditions
      ansible.builtin.debug:
          msg: Fruit_Name is APPLE
      when: fruit_name == "apple"